version: '3.8'

services:
  scraper:
    image: telegraf:1.27.1-alpine
    restart: always
    volumes:
      - ./config/scraper.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - primary

networks:
  primary:
    name: primary
    external: true
